---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 80}]
        - ["forwarded_port", {guest: 443, host: 443}]

suites:
  - name: default
    run_list:
      - recipe[dokuwikime::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
