name 'dokuwikime'
maintainer 'Thomas Holt'
maintainer_email 'twh@pobox.com'
license 'MIT'
description 'Installs dokuwiki on Apache 2.4/PHP 7.2 on CentOS'
log_description 'Installs dokuwiki on Apache 2.4/PHP 7.2 on CentOS.'
version '0.2.0'
chef_version '>= 13.0'
issues_url 'https://github.com/indygwyn/dokuwikime/issues'
source_url 'https://github.com/indygwyn/dokuwikime'
supports 'centos'
supports 'centos7'
depends 'ark'
depends 'selinux_policy'
